name: Test Composite Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run my composite action
        uses: ./.github/actions/my-test-runner
